# Generated by Django 4.2.16 on 2024-11-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryentry_confidence_and_more'),
        ('diary', '0003_entry'),
    ]

    operations = [
    ]
