# Generated by Django 5.1.2 on 2024-11-21 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryentry_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='名前')),
                ('personality', models.CharField(choices=[('introvert', '内向的'), ('extrovert', '外向的'), ('neutral', '中立的')], max_length=20, verbose_name='性格')),
                ('favorite_genre', models.CharField(max_length=200, verbose_name='好きな書籍のジャンル')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介')),
            ],
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='confidence',
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='recommended_book',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='sentiment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
