# Generated by Django 5.1.2 on 2024-11-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_userprofile_user_name_userprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
