# Generated by Django 5.1.2 on 2024-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='analyzed_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='analyzed_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
