# Generated by Django 5.1.2 on 2024-11-25 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_diaryentry_analyzed_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='analyzed_confidence',
            new_name='confidence',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='analyzed_sentiment',
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='recommended_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
